### ISSUE TITLE
您好！请问如何获取流程中压缩图片？

### ISSUE THREAD

**Issue by dmndxld** [Guaishou74851/CASNet#1]
很感谢作者您在CS领域贡献的这份工作，我大受裨益，目前我也在从事相关研究。我想知道该如何获取您在Overview图中第二步骤，经过SS以及IS所得到的Initial Estimation的图片，也就是压缩后尚未恢复的图片。感谢您的回复！

**Comment by Guaishou74851** [comment]
您好，感谢您对本工作的关注！如果您想要在测试时直接获取初始化结果，可以直接在“model_test.py”文件中将第155行（即“forward”方法的“x=PhiT_y”操作）所得到的结果直接进行图像块拼接和返回。具体而言，您可以在第155行之后添加如下两行代码：

```python
    x = F.fold(x, output_size=(h, w), kernel_size=self.B, stride=self.B)
    return x
```

按照预期，此时模型将会直接返回初始化得到的图像，其尺寸应该为：(1,1,h,w)。
