### ISSUE TITLE
您好！我在重现您的工作，恢复图片时遇到了爆显存的问题，请问该如何解决？

### ISSUE THREAD

**Issue by dmndxld** [Guaishou74851/CASNet#2]
您好，再次请教！这次我在重构图片时，显存爆了，恢复失败。具体而言，运行的是test.py文件，但是图片是用的高分辨率遥感图像，图片尺寸为3904x1280，模型是您提供的net_params_320.pkl文件。我首先用单卡A40会爆显存，再尝试了DataParallel下4张A40还是失败，改写成DPP多卡下4张A40也是没有恢复成功。主要是在这一步model_test.py的135行,
`
PhiT_Phi_basic = Phi_basic.permute(0, 2, 1).matmul(Phi_basic)
`
出现OutOfMemory的情况。请问遇到这种高分辨率的图片该怎么恢复呢？

**Comment by Guaishou74851** [comment]
您好，我确实还没有尝试过在这样大尺寸的图像上进行CS采样和重建。根据您提供的信息，模型甚至在还没正式开始用复原子网络（Recovery Subnet，RS）进行重建时就已经爆显存了。我目前的建议是：您可以尝试不直接输入整幅完整的图像，也就是将图像切分为（重叠的或不重叠的）512×512或1024×1024的子图像进行分别处理，然后将子图像们的“采样+重建”的输出结果进行拼合，以得到最终整体的结果。

**Comment by dmndxld** [comment]
> 您好，我确实还没有尝试过在这样大尺寸的图像上进行CS采样和重建。根据您提供的信息，模型甚至在还没正式开始用复原子网络（Recovery Subnet，RS）进行重建时就已经爆显存了。我目前的建议是：您可以尝试不直接输入整幅完整的图像，也就是将图像切分为（重叠的或不重叠的）512×512或1024×1024的子图像进行分别处理，然后将子图像们的“采样+重建”的输出结果进行拼合，以得到最终整体的结果。

感谢您的建议，目前恢复效果也是相当好，谢谢！
